artifacts_root: artifacts

#for data ingestion config 
data_ingestion:
  root_dir: artifacts/data_ingestion    # create a directory name data_ingestion
  source_URL: https://github.com/amitmaji01/data_set/raw/main/flight_data.zip # define the source url
  local_data_file: artifacts/data_ingestion/data.zip   # store the data as a zip formal 
  unzip_dir: artifacts/data_ingestion   # store the data in uzip format in that directory